### ISSUE TITLE
Update Bootstrap to v4

### ISSUE THREAD

**Issue by tjaskula** [Luteceo/aspnet-starter-kit-2.0#24]
Sample code is based on Bootstrap 3 so it should be updated to Bootstrap 4

**Comment by Psvensso** [comment]
First of all, great template! Was about to build one myself when i stumbled on this, was really missing the old asp.net template! 

Regarding this issue, 
i was about to have a look at it when i started to wonder, right now the template has minimum of styling, the examples really just use some bootstrap classes.
 
Should the template really contain any opinionated style framework? 

People are using more and more css-from-js framework, i wanted to use ant-design for example. 

My opinion in the matter is rather to remove the css lib alltogether and clean up the examples. Then add a opt-in CSS and/or SASS loader then people can add whatever framework dependency they want. 

And-design, Reactstrap (for bootstrap 4 for example). 

I´ll be happy to create a PR.

**Comment by tjaskula** [comment]
Thanks @Psvensso for you ideas. I don't want to stick particularly to bootstrap so I'll be happy to accept you PR if finally we can get rid of it 👍

**Comment by tjaskula** [comment]
Adressed with #45
