### ISSUE TITLE
Server-side rendering to prevent white flash

### ISSUE THREAD

**Issue by flipdoubt** [Luteceo/aspnet-starter-kit-2.0#47]
Does anyone have experience integrating server-side rendering with this starter kit's workflow? I'm trying to prevent that white flash that occurs loading a new page.

**Comment by tjaskula** [comment]
Could you describes more precisely what have you tried and what is not working properly ?

**Comment by flipdoubt** [comment]
Nothing works improperly so much as not as well as expected. I was hoping an example of a properly rendered site would show me what I'm doing wrong.

I'm in the early stages of adapting this template to [my project](https://github.com/flipdoubt/navwrist-web), and I've found a [simple test view](https://github.com/flipdoubt/navwrist-web/blob/master/server/Views/Home/Index.cshtml) with some [fairly simple components](https://github.com/flipdoubt/navwrist-web/tree/master/client/components/Home) momentarily loads a blank screen (white flash) before the [static css](https://github.com/flipdoubt/navwrist-web/blob/master/client/css/site.css) applies a dark background.

Any idea what I'm doing wrong?

**Comment by flipdoubt** [comment]
So I discovered what the issue is on my side with the styling, so I can close this issue. Still, I think it would help to include in this example some SSR components.
